image: hseeberger/scala-sbt:8u242_1.3.8_2.12.10

variables:
  SBT_OPTS: >
    -Dsbt.global.base=$CI_PROJECT_DIR/sbt-cache/sbtboot
    -Dsbt.boot.directory=$CI_PROJECT_DIR/sbt-cache/boot
    -Dsbt.ivy.home=$CI_PROJECT_DIR/sbt-cache/ivy
cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
      - "$CI_PROJECT_DIR/sbt-cache"

stages:
  - test
  - assembly

test-2.4:
  stage: test
  script:
    - ./scripts/test-only-spark2.sh
  coverage: '/Statement coverage.: (.*\%)/'

assembly-2.4:
  stage: assembly
  script:
    - sbt "project core" 'set sparkVersion:="2.4.0"' assembly
